<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718165811 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE journal_article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, rubrique VARCHAR(60) NOT NULL, temps_lecture INT NOT NULL, chapo TEXT NOT NULL, corps TEXT NOT NULL, auteur VARCHAR(120) NOT NULL, seo_title VARCHAR(180) DEFAULT NULL, seo_description VARCHAR(320) DEFAULT NULL, publie_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D2814083989D9B62 ON journal_article (slug)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE journal_article');
    }
}
